services:

  redis:
    command: /bin/sh -c "redis-server --requirepass $$REDIS_PASSWORD"
    image: redis:alpine
    env_file: ./docker/secrets.env

  mongodb:
    image: mongo:latest
    env_file: ./docker/secrets.env
    volumes:
      - db-data:/data/db

  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
      args:
        ENABLED_MODULES: geoip
    ports:
      - "8080:80"
    volumes:
      - ./docker/static/:/opt/jschan/static/
    depends_on:
      - jschan

  jschan:
    build:
      context: .
      dockerfile: ./docker/jschan/Dockerfile
    env_file: ./docker/secrets.env
    environment:
      - NODE_ENV=development
    volumes:
      - ./docker/static:/opt/jschan/static/
    depends_on:
      - redis
      - mongodb

volumes:
  db-data:

