FROM node:lts

WORKDIR /opt/jschan

COPY . .

RUN npm install

RUN npm i -g pm2 gulp

COPY ./docker/jschan/secrets.js ./configs/secrets.js

#i fucking hate docker
ENV MONGO_USERNAME jschan
ENV MONGO_PASSWORD changeme
ENV REDIS_PASSWORD changeme

CMD ["/bin/sh", "-c", "gulp generate-favicon; gulp reset; gulp"]
